language: node_js
node_js:
- 13
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: XxvbSYfajq7dXW9dk0hEbsWEjzXx7tH9VF4IdCVh8TE+c0BozgHygP0xhZSurGJDFEi7DnrtHDB4PcvKj1iYIclq+3N6A8bCOJVkX05UeG07SJZ9C3UuLGzarvt7+AyYF8eYoPFo19ISVLScKHMXt45NTFz3EakhCFINPz2f33zHgrO/jfO1x4eWQ3pM/jO9sZqEiTdOMQ1akO+u/sKIyXxkdIyrde/TI+QWXD8Jc1tWULn6eW2kDUVVVHqsmQh33+IiqsF4/Oj5vfUZsXEn5St7qMq+d64pAMKyFS3ccneWRhCIPm9CIVeBBVuLh4H/oODhjOuz4s/5V90Jqx/dahzi4nvy25bakHO/ab8fsMtcwTgwzg9RdGDr4G0ilj24SWHYwh4YS94v/9N8DxlxRlYe/tTV7MCzJjNIEon0LX2tWUZRi0eiVe7d33b/wrQgxB8TDpKbznEFu7KuLERzV6cBZ3bG3jPTh6Btuw2KM4w0pqZW4dF05z+0kVl293YjzJ23E26uwbwHwJFFrRGhK60Cu9k74V1n6dXVPokdFZokVtNIc1foyCsEoT2Lnphnje0iF6nIziBawR89DcBvO5bMOfKWln6iFo+C/sCC1EXiciaGZWwgbTmC5QhWRf4kmvZgPz0R70Gk2pJMG5apMFqGTTQnmu7nfgjnxrvMSIM=
  app: play-your-cats-right
  on:
    repo: jonesandy/play-your-cats-right
