language: node_js
node_js:
- 13
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: lHvJ4yIgj8z0KfanIOrdCgim0Bx32fapCQybMNKG2oqH3rZ9XVsprEdzT/72qTemqDsajVQpEiTrPlC5LvPCm14MgnpwZ2HfLC06ftapnh9AeZfNuBbBMK7RD6jixgB1LlnQ2JRQvWH7epaj4EO9TyL573/kUjW1iIDSVbzBWI2HkwL4G+LUpkWZWol3gDtJ+m6Rg8BJlhTk/3aYDWTys+z+UgHTdaWO9MPemelbKKvjYGc6vHr59l0/PmGMYelVKEBMlwt+bjh5Fiys4O05UV3k3ob7Or159c6QeXfVg9T62oMBlV5Y88wI21DyT/bZlrEb9Q4Oij0BeJ5slmm3odSAiJZdJ6uysqvIME2MWKRRrPocmkZtIB2gQ9SMtU4n2SF600hWfeJKR/Cv3RVKYrV9UjqLWnhmNnNcntL1DI2BCiU6cYjCa/PfTSBGwZFu5CETCTCzGJQW9KgYBEDjnCYK0VelFO896UPDiBVtHyGcJ/XcKgfZPcECG/9kFb4QBx9vant8Wsh+hN2Zn70QA7Vfu7iwctM5OcL21UYQn3vn8nGUbxoGXurnsqCEVztUKISuTOXCHIBWOVUszYU15pIks3bGT2NMJJpnJDiLGVyJ4ODRNknccaWWU7H3Hhzc/QMFTNIdGi0UAWXPzdyEhiIYm8aGYRJt4pAUIAK4FRA=
