language: node_js
node_js:
- 13
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: blKH5kt3NCJFm1I6P2g5etLIiljaUS9x1QvnOGD3ymOp7IZl5DY+5I2IuEYNCNg6MJ6FEAWBp+kjRMMjaDsAhkiwtTjisxNFrAS5jucEwp1wnb314YZmT72cqRb9Q94outdeV4yNw6Ccv85YPIr3/rp8paqilV/kayCsOxbazHaHS4VN/Ri4XvbJ5SaSWB3KIwL9WKj45kmddwzcwZ31AbeRKwRPLGsSodhkwNfZG6sO7Dm6Nj4He7o4tid8UyRQssdl1tClDv/KaAwGchPJblQUiDY1wFT8NU8ds/QkxGpTMbcxtEq+kHts8RvE+PouqwDT3N+dfvNzfP4nosuODQP6H6RHavdoH9+a/06FgFvOeQ5B4V0MqOOyTFvzwRTwphdCYt110RnUkFyBUK/IHyBRkuq420IMDOUSZJ4T4BrMQZ6TZFQ2sWxiVYh8WgdiXNp5DALFoerxaiGJdLADBLlzq68HBVxfYDPClJspUH7btzD6J+dCoqWxnB0AeD7DzH7L0QYL4HvRY6mwA0NzQ2XNsvt0O4XrUmMK2fuVhlotqxn0/yCSle5I401b5zbys9nZNb46c/HrC51es8M5oXDcWZD33dusGQMDCMf1cH1DgVePnEZkvHLaPVdlEXMhsWMlf2tCK/HeGK6D3qyDBiHoBmLep5ZNkLtH15+ENfc=
  app: play-your-cats-right
  on:
    repo: jonesandy/play-your-cats-right
